/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NbTvnAjVPQS
 */

"use client"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Select from "./Select";
import { useState } from "react";

export function Navbar() {
    const options = ["옵션 1", "옵션 2", "옵션 3"];
       const [isOpen, setIsOpen] = useState(false);

       // 네비게이션 바를 토글하는 함수
       const toggleNavbar = () => {
         setIsOpen(!isOpen);
       };


      
  return (
    <nav className='bg-gray-800 text-white p-4'>
      <div className='container mx-auto flex justify-between items-center'>
        <div className='flex items-center'>
          <img src='1.jpeg' alt='Logo' className='h-12 w-8 object-cover mr-4' />
          <Select options={options} placeholder='옵션을 선택하세요' />
        </div>
        <div className='md:hidden'>
          <button
            onClick={toggleNavbar}
            className='text-white px-3 py-2 rounded-md'
          >
            {/* SVG for three dots */}
            <svg
              className='h-6 w-6'
              fill='none'
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth='2'
              viewBox='0 0 24 24'
              stroke='currentColor'
            >
              <path d='M4 6h16M4 12h16m-7 6h7'></path>
            </svg>
          </button>
        </div>

        <div
          className={`flex flex-col md:flex-row md:items-center ${
            isOpen ? "block" : "hidden"
          } `}
        >
          <a
            href='#'
            className='text-white px-3 py-2 rounded-md hover:bg-gray-700'
          >
            항목 1
          </a>
          <a
            href='#'
            className='text-white px-3 py-2 rounded-md hover:bg-gray-700'
          >
            항목 2
          </a>
          <div className='relative'>
            <button className='text-white px-3 py-2 rounded-md hover:bg-gray-700'>
              드롭다운
            </button>
            <div className='absolute hidden bg-gray-700 text-white right-0 mt-2 py-2 w-48'>
              <a href='#' className='block px-4 py-2 hover:bg-gray-600'>
                서브 항목 1
              </a>
              <a href='#' className='block px-4 py-2 hover:bg-gray-600'>
                서브 항목 2
              </a>
            </div>
          </div>
        </div>

        <div className=' items-center hidden md:flex '>
          <button className='bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-2'>
            버튼 1
          </button>
          <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>
            버튼 2
          </button>
        </div>
      </div>
    </nav>
  );
}
